# Generated by Django 3.1.4 on 2023-03-23 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_userfollows'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
